### ISSUE TITLE
Response "404 NotFound - Not Found - Brak danych" while trying get data from Table B

### ISSUE THREAD

**Issue by marcinchus** [maciej-sz/nbp-php#15]
The problem is that probably due to a change in the update logic of Table B (https://nbp.pl/statystyka-i-sprawozdawczosc/kursy/informacja-o-terminach-publikacji-kursow-walut) , currently Table B is empty (https://api.nbp.pl/api/exchangerates/tables/B/2024-08-04/2024-08-05) and this causes a problem also with retrieving data from Table A in this method: https://github.com/maciej-sz/nbp-php/blob/7734e5e3c5ec37b1fa77706bf7de0c822189ea91/src/Service/CurrencyAverageRatesService.php#L49

**Comment by supernrm** [comment]
`$currencyAverages->fromDayBefore('2024-08-01')->fromTable('A')->getRate('EUR');`

HTTP/1.1 404 Not Found - Brak danych returned for "https://api.nbp.pl/api/exchangerates/tables/B/2024-08-01/2024-08-06".

@maciej-sz projekt jest porzucony?
