### ISSUE TITLE
Invalid keys in cache implementation

### ISSUE THREAD

**Issue by michalananapps** [maciej-sz/nbp-php#22]
The current implementation does not adhere to the PSR-6 specification for cache keys. According to the PSR-6 specification, the following characters are not allowed in cache keys: {}, (), \, /, @, and :. However, the library is currently using URL paths as cache keys, which contain the `/` character (for example `/api/cenyzlota/2023-03-01/2023-03-31`).

It results in the exception message `Symfony\Component\Cache\Exception\InvalidArgumentException: Cache key "/api/cenyzlota/2023-03-01/2023-03-31" contains reserved characters "{}()/\@:"` when using any Symfony PSR-6 adapter.

**Comment by michalananapps** [comment]
@maciej-sz Are you planning to release a new version/tag with this fix?

**Comment by maciej-sz** [comment]
@michalananapps yeah, as soon as I fix the ci
